services:
  proxy:
    image: nginx
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx:/etc/nginx
      - ../frontend/dist:/data/www
  
  api:
    image: node
    volumes:
      - ./api:/api
    working_dir: /api
    command: node api.js