services:
  dev-server:
    image: node
    depends_on:
      - api
    volumes:
      - ../frontend:/frontend
    working_dir: /frontend
    command: npm run dev
    ports:
      - 5173:5173

  api:
    image: node
    volumes:
      - ./api:/api
    working_dir: /api
    command: node api.js
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: samzofkie
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql