services:
  dev-server:
    image: node
    depends_on:
      - api
    volumes:
      - ../frontend:/frontend
    working_dir: /frontend
    command: npm run dev
    ports:
      - 5173:5173

  api:
    image: node
    depends_on:
      - db
    restart: on-failure:10
    volumes:
      - ./api:/api
    working_dir: /api
    command: node api.js

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: xGfKqmOznGVrzHc40WY-Y
      POSTGRES_DB: jailsolidaritynetwork
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql