services:
  dev-server:
    image: node
    volumes:
      - ../frontend:/frontend
      - ./documents:/frontend/public/documents
    working_dir: /frontend
    command: npm run dev
    ports:
      - 5173:5173

  api:
    image: node
    volumes:
      - ./api:/api
      - ./documents:/documents
    working_dir: /api
    env_file: ./api/.env
    command: node api.js

  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: xGfKqmOznGVrzHc40WY-Y
      POSTGRES_DB: jailsolidaritynetwork
    volumes:
      - ./db:/docker-entrypoint-initdb.d