services:
  proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - ../frontend/dist:/data/www
      - ../frontend/public/static:/data/static
      - ./documents:/data/documents
      - ./logs:/logs

  api:
    image: node
    restart: always
    volumes:
      - ./api:/api
      - ./documents:/api/documents
    working_dir: /api
    env_file: ./api/.env
    command: node api.js

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: xGfKqmOznGVrzHc40WY-Y
      POSTGRES_DB: jailsolidaritynetwork
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
