services:
  proxy:
    image: nginx
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx:/etc/nginx
      - ../frontend/dist:/data/www
    depends_on:
      - db

  api:
    image: node
    volumes:
      - ./api:/api
    restart: on-failure:10
    working_dir: /api
    command: node api.js

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: xGfKqmOznGVrzHc40WY-Y
      POSTGRES_DB: jailsolidaritynetwork
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
